# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'staffionative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for staffionative

  target 'staffionative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'staffionativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'staffionative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for staffionative-tvOS

  target 'staffionative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
